### ISSUE TITLE
Fix broken keyword notifications

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#587] opened 2024-07-28 12:16 UTC
It seems that the notifications for custom keywords are broken. I am receiving notifications for region and IP address, for example. But when I put in "Batman" as general keyword and enter "Batman" on imdb.com, I am not receiving a notification.

**Comment by dadak-dom** [comment] 2024-07-29 15:08
I was able to reproduce the bug using the version that you download from the web store, but it looks like this has already been fixed in the latest version of the main branch. I'll probably update the extension on the web store soon when I get the chance. @atlasharry , could you verify that the keyword notifications also work for you when running the latest extension version? (i.e., [the steps outlined here](https://github.com/privacy-tech-lab/privacy-pioneer?tab=readme-ov-file#3-development))

**Comment by atlasharry** [comment] 2024-07-30 09:27
@dadak-dom Yes! I will verify this tonight!

**Comment by SebastianZimmeck** [comment] 2024-07-30 15:21
> Your Extension has been automatically screened and tentatively approved. It is now available at https://addons.mozilla.org/addon/privacy-pioneer/.
> 
> Your add-on can be subject to human review at any time. Reviewers may determine that it requires changes or should be removed. If that occurs, you will receive a separate notification with details and next steps.
> 
> Approved versions: 1.2.3
> 
> Comments: This version has been screened and approved for the public. Keep in mind that other reviewers may look into this version in the future and determine that it requires changes or should be taken down.
> 
> Thank you!.

Nice! Feel free to close, @dadak-dom.

**Comment by SebastianZimmeck** [comment] 2024-07-30 21:28
After half a day of use, I can say that v1.2.3 is the best version yet. A joy to use! Well done, @dadak-dom and @atlasharry!

**Closed** 2024-07-31 13:12 UTC
Labels: bug, low priority
